default: &default
  adapter: postgresql
  encoding: utf8
  pool: 25
  host: localhost
  username: postgres
  password: ''
development:
  <<: *default
  database: blog_development
test:
  <<: *default
  database: blog_test
