default: &default
  adapter: postgresql
  encoding: utf8
  pool: 25
  host: localhost
  database: little_grass_2919
  username: rxkhwcw4uu4a8mkf
  password: cJ85yGYELdvb3hJfhjkHJSBJ-UTyDF-d
development:
  <<: *default
  username: simonyang
  password: ''
  database: blog_development
test:
  <<: *default
  database: blog_test
